name: Build and Push Docker Image

on:
  #push:
  #  branches:
  #    - main # Trigger on push to the main branch
  workflow_dispatch: 

env:
  DOCKER_IMAGE_NAME: stremio-jackett-enhanced
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true 
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

      - name: Verify image push
        run: echo "Image ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }} pushed successfully!"
